import type { Section } from "@/lib/types";

/** Home layout used when no published `home` page exists in the database. Mirrors supabase/seed.sql. */
export const defaultHome: Section[] = [
  { id: "hero", type: "hero", media: { kind: "image", url: "" }, eyebrow: { cs: "Televize 2026 · JVC QLED", en: "TV 2026 · JVC QLED" }, title: { cs: "Velký obraz, malá cena.", en: "Big picture, small price." }, text: { cs: "JVC 65\" QLED s Mini LED podsvícením, Google TV, HDR10+ a Dolby Atmos. Naladíme a zavěsíme u vás doma.", en: "The 65-inch JVC QLED with Mini LED backlighting, Google TV, HDR10+ and Dolby Atmos. Tuned and wall-mounted at your home." }, cta: { label: { cs: "Prohlédnout", en: "View" }, href: "/produkt/jvc-lt-65vgm9435/" }, productSlug: "jvc-lt-65vgm9435", align: "left", height: "large", overlay: 60 },
  { id: "cats", type: "categories", eyebrow: { cs: "Sortiment", en: "Range" }, title: { cs: "Všechno pro domácnost, dílnu i zahradu.", en: "Everything for the home, the workshop and the garden." }, text: { cs: "Elektro a domácí spotřebiče prodáváme od roku 1990. Šest prodejen, jeden e-shop a lidé, kteří vám poradí, zapojí a opraví.", en: "We have sold electronics and appliances since 1990. Six stores, one online shop and people who advise, install and repair." }, categories: ["televize-audio", "velke-spotrebice", "male-spotrebice", "pocitace-telefony", "naradi", "zahrada"] },
  { id: "featured", type: "products", eyebrow: { cs: "Vybrané produkty", en: "Featured products" }, title: { cs: "Právě skladem", en: "In stock now" }, source: "featured", limit: 8 },
  { id: "campaign", type: "banner", media: { kind: "image", url: "" }, eyebrow: { cs: "Velké spotřebiče", en: "Large appliances" }, title: { cs: "Dovezeme, zapojíme, starý odvezeme.", en: "Delivered, installed, the old one taken away." }, text: { cs: "Pračky, chladničky a myčky Gorenje, Philco, Romo a Hisense. Vlastní doprava po Vysočině a Pardubickém kraji, odvoz starého spotřebiče zdarma.", en: "Gorenje, Philco, Romo and Hisense washers, fridges and dishwashers. Our own delivery across Vysočina and the Pardubice region, old appliance removed free." }, cta: { label: { cs: "Zobrazit spotřebiče", en: "See appliances" }, href: "/velke-spotrebice/" } },
  { id: "stores", type: "split", media: { kind: "image", url: "" }, eyebrow: { cs: "Prodejny", en: "Stores" }, title: { cs: "Šest prodejen, kde si zboží sáhnete.", en: "Six stores where you can touch the goods." }, text: { cs: "Golčův Jeníkov, Čáslav, Chotěboř, Světlá nad Sázavou, Třemošnice a Heřmanův Městec. Objednávku z e-shopu si na každé vyzvednete zdarma.", en: "Golčův Jeníkov, Čáslav, Chotěboř, Světlá nad Sázavou, Třemošnice and Heřmanův Městec. Collect your online order free at any of them." }, cta: { label: { cs: "Najít prodejnu", en: "Find a store" }, href: "/prodejny/" }, mediaSide: "right" },
  { id: "news", type: "news", limit: 3 },
  { id: "brands", type: "brands", eyebrow: { cs: "Značky", en: "Brands" }, title: { cs: "Značky, které prodáváme a servisujeme", en: "Brands we sell and service" } },
  { id: "service", type: "split", media: { kind: "image", url: "" }, eyebrow: { cs: "Servis", en: "Service" }, title: { cs: "Servis a poradenství pod jednou střechou.", en: "Service and advice under one roof." }, text: { cs: "Autorizovaný servis zahradní techniky VARI a AL-KO, opravy nářadí Einhell a Graphite, reklamace spotřebičů a nastavení počítačů.", en: "Authorised VARI and AL-KO garden machinery service, Einhell and Graphite tool repairs, appliance claims and computer set-up." }, cta: { label: { cs: "Více o servisu", en: "About our service" }, href: "/servis/" } },
];

const FEATURED = ["jvc-lt-65vgm9435", "gorenje-n62-cs2xl4", "delonghi-ecam-290-51-b-magnifica-evo", "graphite-energy-plus-58g020", "vari-rl-98-hw", "xiaomi-redmi-note-14-5g-256gb", "sencor-sfr-5010-bk", "philco-pldi-148-asw"];
export const defaultFeatured = FEATURED;
