import type { Section } from "@/lib/types";

/** Home layout used when no published `home` page exists in the database. Mirrors supabase/seed.sql. */
export const defaultHome: Section[] = [
  { id: "hero", type: "hero", media: { kind: "image", url: "" }, eyebrow: { cs: "Televize 2026 · LG OLED", en: "TV 2026 · LG OLED" }, title: { cs: "Černá, jak má být.", en: "Black, the way it should be." }, text: { cs: "LG OLED B4 v 65 palcích: dokonalý kontrast, 120 Hz pro konzole a Dolby Vision. Naladíme a zavěsíme u vás doma.", en: "The 65-inch LG OLED B4: perfect contrast, 120 Hz for consoles and Dolby Vision. Tuned and wall-mounted at your home." }, cta: { label: { cs: "Prohlédnout", en: "View" }, href: "/produkt/lg-oled65b4/" }, productSlug: "lg-oled65b4", align: "left", height: "large", overlay: 60 },
  { id: "cats", type: "categories", eyebrow: { cs: "Sortiment", en: "Range" }, title: { cs: "Všechno pro domácnost, dílnu i zahradu.", en: "Everything for the home, the workshop and the garden." }, text: { cs: "Elektro a domácí spotřebiče prodáváme od roku 1990. Šest prodejen, jeden e-shop a lidé, kteří vám poradí, zapojí a opraví.", en: "We have sold electronics and appliances since 1990. Six stores, one online shop and people who advise, install and repair." }, categories: ["televize-audio", "velke-spotrebice", "male-spotrebice", "pocitace-telefony", "naradi", "zahrada"] },
  { id: "featured", type: "products", eyebrow: { cs: "Vybrané produkty", en: "Featured products" }, title: { cs: "Právě skladem", en: "In stock now" }, source: "featured", limit: 8 },
  { id: "campaign", type: "banner", media: { kind: "image", url: "" }, eyebrow: { cs: "Velké spotřebiče", en: "Large appliances" }, title: { cs: "Dovezeme, zapojíme, starý odvezeme.", en: "Delivered, installed, the old one taken away." }, text: { cs: "Pračky, chladničky a myčky Bosch, Whirlpool, LG a Gorenje. Vlastní doprava po Vysočině a Pardubickém kraji, odvoz starého spotřebiče zdarma.", en: "Bosch, Whirlpool, LG and Gorenje washers, fridges and dishwashers. Our own delivery across Vysočina and the Pardubice region, old appliance removed free." }, cta: { label: { cs: "Zobrazit spotřebiče", en: "See appliances" }, href: "/velke-spotrebice/" } },
  { id: "stores", type: "split", media: { kind: "image", url: "" }, eyebrow: { cs: "Prodejny", en: "Stores" }, title: { cs: "Šest prodejen, kde si zboží sáhnete.", en: "Six stores where you can touch the goods." }, text: { cs: "Golčův Jeníkov, Čáslav, Chotěboř, Světlá nad Sázavou, Třemošnice a Heřmanův Městec. Objednávku z e-shopu si na každé vyzvednete zdarma.", en: "Golčův Jeníkov, Čáslav, Chotěboř, Světlá nad Sázavou, Třemošnice and Heřmanův Městec. Collect your online order free at any of them." }, cta: { label: { cs: "Najít prodejnu", en: "Find a store" }, href: "/prodejny/" }, mediaSide: "right" },
  { id: "news", type: "news", limit: 3 },
  { id: "brands", type: "brands", eyebrow: { cs: "Značky", en: "Brands" }, title: { cs: "Značky, které prodáváme a servisujeme", en: "Brands we sell and service" } },
  { id: "service", type: "split", media: { kind: "image", url: "" }, eyebrow: { cs: "Servis", en: "Service" }, title: { cs: "Servis a poradenství pod jednou střechou.", en: "Service and advice under one roof." }, text: { cs: "Autorizovaný servis zahradní techniky VARI a Husqvarna, opravy nářadí Narex, reklamace spotřebičů a nastavení počítačů.", en: "Authorised VARI and Husqvarna garden machinery service, Narex tool repairs, appliance claims and computer set-up." }, cta: { label: { cs: "Více o servisu", en: "About our service" }, href: "/servis/" } },
];

const FEATURED = ["lg-oled65b4", "bosch-wgg244a0by", "delonghi-magnifica-start-ecam220-22", "makita-dhp485rfj", "vari-sekacka-ctp-4650-lpe", "samsung-galaxy-a56-5g-128gb", "tefal-easy-fry-xxl-ey8018", "gorenje-nrk6192aw4"];
export const defaultFeatured = FEATURED;
