#!/usr/bin/env node
/* Generate supabase/seed.sql from src/data/catalog.ts, src/data/stores.ts, src/data/shipping.ts,
   src/lib/defaultHome.ts and src/lib/i18n.tsx. Run `node scripts/seed.mjs` after editing any of them. */
import { readFileSync, writeFileSync } from "node:fs";
import ts from "typescript";

/** Transpile a TS module and evaluate it with the given module map standing in for `@/…` imports. */
function load(file, modules = {}) {
  const src = readFileSync(file, "utf8");
  const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.React } }).outputText;
  const mod = { exports: {} };
  new Function("module", "exports", "require", js)(mod, mod.exports, (name) => modules[name] ?? {});
  return mod.exports;
}
const catalog = load("src/data/catalog.ts");
const storesMod = load("src/data/stores.ts");
const shipping = load("src/data/shipping.ts", { "@/data/stores": storesMod });
const home = load("src/lib/defaultHome.ts");
const i18n = load("src/lib/i18n.tsx", { react: { createContext: () => ({}), useContext: () => ({}), useEffect: () => {}, useState: () => [] } });
const { products, categories } = catalog;
const { company } = storesMod;

const q = (v) => v === undefined || v === null ? "null" : `'${String(v).replace(/'/g, "''")}'`;
const j = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const arr = (a) => `array[${(a ?? []).map(q).join(",")}]::text[]`;

let sql = `-- generated by scripts/seed.mjs · ${new Date().toISOString()}\n`;
sql += `insert into public.categories (slug, label, blurb, sort) values\n` + categories.map((c, i) =>
  `(${q(c.slug)}, ${j(c.label)}, ${j(c.blurb)}, ${i})`).join(",\n") +
  `\non conflict (slug) do update set label = excluded.label, blurb = excluded.blurb, sort = excluded.sort;\n\n`;

sql += `insert into public.products (slug, brand, category, name, price, old_price, energy_class, power, size, short, specs, colors, tags, status, stock, featured, sort) values\n` +
  products.map((p, i) => `(${q(p.slug)}, ${q(p.brand)}, ${q(p.category)}, ${q(p.name)}, ${p.price}, ${p.oldPrice ?? "null"}, ${q(p.energy)}, ${q(p.power)}, ${q(p.size)}, ${j(p.short)}, ${j(p.specs)}, ${j(p.colors)}, ${arr(p.tags)}, 'active', ${catalog.isBulky(p.category) ? 3 : 12}, ${home.defaultFeatured.includes(p.slug)}, ${i})`).join(",\n") +
  `\non conflict (slug) do update set brand = excluded.brand, category = excluded.category, name = excluded.name, price = excluded.price, old_price = excluded.old_price, energy_class = excluded.energy_class, power = excluded.power, size = excluded.size, short = excluded.short, specs = excluded.specs, colors = excluded.colors, tags = excluded.tags, sort = excluded.sort;\n\n`;

sql += `insert into public.shipping_methods (id, carrier, name, description, price, free_over, enabled, needs_pickup_point, bulky, sort) values\n` +
  shipping.defaultShippingMethods.map((s) => `(${q(s.id)}, ${q(s.carrier)}, ${j(s.name)}, ${j(s.description)}, ${s.price}, ${s.free_over ?? "null"}, ${s.enabled}, ${!!s.needs_pickup_point}, ${!!s.bulky}, ${s.sort})`).join(",\n") +
  `\non conflict (id) do nothing;\n\n`;

sql += `insert into public.payment_methods (id, name, enabled, test_mode, config, sort) values\n` +
  shipping.defaultPaymentMethods.map((p) => `(${q(p.id)}, ${j(p.name)}, ${p.enabled}, true, '{}'::jsonb, ${p.sort})`).join(",\n") + `\non conflict (id) do nothing;\n\n`;

const settings = {
  store: { name: company.name, legal: company.legal, address: company.address, phone: company.phone, email: company.email, ico: company.ico, dic: company.dic, hours: company.hours, currency: "CZK", locales: ["cs", "en"], defaultLocale: "cs" },
  theme: { accent: "#111111", signal: "#d0021b", font: "Inter", radius: 0, buttonStyle: "uppercase" },
  announcement: { enabled: true, text: i18n.dict.topbar },
  taxes: { vatRate: 21, pricesIncludeVat: true },
  notifications: { orderEmailTo: company.email, customerConfirmation: true },
  checkout: { allowGuest: true, termsUrl: "/obchodni-podminky/", requirePhone: true },
};
sql += `insert into public.settings (key, value) values\n` + Object.entries(settings).map(([k, v]) => `(${q(k)}, ${j(v)})`).join(",\n") + `\non conflict (key) do nothing;\n\n`;

sql += `insert into public.pages (slug, title, sections, status) values ('home', ${j({ cs: "Domů", en: "Home" })}, ${j(home.defaultHome)}, 'published')\non conflict (slug) do nothing;\n`;

writeFileSync("supabase/seed.sql", sql);
console.log(`wrote supabase/seed.sql (${products.length} products, ${categories.length} categories, ${shipping.defaultShippingMethods.length} shipping methods)`);
